In [319]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchtext

from torchtext import data
from torchtext import datasets

import spacy
import numpy as np

import time
import random
import os

In [320]:
def read_data(base_dir, datafields):
    train = []
    val = []
    test = []
    for filename in sorted(os.listdir(base_dir)):
        if str(filename) < 'wsj_0100.dp': # get train data
            with open(base_dir + filename, encoding='utf-8') as f:
                words = []
                labels = []
                for line in f:
                    line = line.strip()
                    if line: # if is not empty string
                        columns = line.split()
                        words.append(columns[0]) # take the word
                        labels.append(columns[-2]) # take the POS tag
                train.append(torchtext.data.Example.fromlist([words, labels], datafields))
        elif str(filename) < 'wsj_0150.dp':
            with open(base_dir + filename, encoding='utf-8') as f:
                words = []
                labels = []
                for line in f:
                    line = line.strip()
                    if line: # if is not empty string
                        columns = line.split()
                        words.append(columns[0]) # take the word
                        labels.append(columns[-2]) # take the POS tag
                val.append(torchtext.data.Example.fromlist([words, labels], datafields))
        else:
            with open(base_dir + filename, encoding='utf-8') as f:
                words = []
                labels = []
                for line in f:
                    line = line.strip()
                    if line: # if is not empty string
                        columns = line.split()
                        words.append(columns[0]) # take the word
                        labels.append(columns[-2]) # take the POS tag
                test.append(torchtext.data.Example.fromlist([words, labels], datafields))
    return torchtext.data.Dataset(train, datafields), torchtext.data.Dataset(val, datafields), torchtext.data.Dataset(test, datafields)

In [321]:
text = data.Field(lower = True)
label = data.Field(unk_token = None)
fields = [('text', text), ('label', label)]
base_dir = '../dependency_treebank/'
train_data, val_data, test_data = read_data(base_dir, fields)

In [322]:
MIN_FREQ = 2

text.build_vocab(train_data, 
                 min_freq = MIN_FREQ,
                 vectors = "glove.6B.100d",
                 unk_init = torch.Tensor.normal_)


label.build_vocab(train_data)

We can check how many tokens and tags are in our vocabulary by getting their length:

In [323]:
print(f"Unique tokens in text vocabulary: {len(text.vocab)}")
print(f"Unique tokens in label vocabulary: {len(label.vocab)}")

Unique tokens in text vocabulary: 3389
Unique tokens in label vocabulary: 46


Exploring the vocabulary, we can check the most common tokens within our texts:

In [324]:
print(text.vocab.freqs.most_common(20))

[(',', 2525), ('the', 2286), ('.', 1896), ('of', 1155), ('to', 1018), ('a', 1000), ('in', 932), ('and', 804), ('for', 448), ("'s", 424), ('that', 413), ('``', 397), ("''", 388), ('$', 332), ('is', 315), ('said', 311), ('it', 301), ('on', 254), ('mr.', 223), ('at', 217)]


We can see the vocabularies for both of our tags:

In [325]:
print(label.vocab.itos)

['<pad>', 'NN', 'NNP', 'IN', 'DT', 'NNS', 'JJ', ',', '.', 'VBD', 'RB', 'CD', 'VB', 'CC', 'VBZ', 'TO', 'VBN', 'PRP', 'VBG', 'VBP', 'MD', 'PRP$', '``', 'POS', "''", '$', ':', 'WDT', 'JJR', 'WP', 'RP', 'NNPS', 'WRB', 'JJS', 'RBR', '-RRB-', '-LRB-', 'EX', 'RBS', 'LS', 'PDT', 'WP$', 'FW', '#', 'SYM', 'UH']


We can also see how many of each tag are in our vocabulary:

In [326]:
print(label.vocab.freqs.most_common())

[('NN', 6131), ('NNP', 5104), ('IN', 4852), ('DT', 3990), ('NNS', 2966), ('JJ', 2948), (',', 2526), ('.', 1917), ('VBD', 1518), ('RB', 1463), ('CD', 1414), ('VB', 1178), ('CC', 1124), ('VBZ', 1097), ('TO', 1015), ('VBN', 1012), ('PRP', 929), ('VBG', 740), ('VBP', 717), ('MD', 405), ('PRP$', 404), ('``', 402), ('POS', 398), ("''", 393), ('$', 336), (':', 285), ('WDT', 199), ('JJR', 155), ('WP', 135), ('RP', 134), ('NNPS', 94), ('WRB', 91), ('JJS', 90), ('RBR', 85), ('-RRB-', 55), ('-LRB-', 52), ('EX', 48), ('RBS', 19), ('LS', 10), ('PDT', 9), ('WP$', 6), ('FW', 2), ('UH', 1), ('SYM', 1), ('#', 1)]


We can also view how common each of the tags are within the training set:

In [327]:
def tag_percentage(tag_counts):
    
    total_count = sum([count for tag, count in tag_counts])
    
    tag_counts_percentages = [(tag, count, count/total_count) for tag, count in tag_counts]
        
    return tag_counts_percentages

In [328]:
print("Tag\t\tCount\t\tPercentage\n")

for tag, count, percent in tag_percentage(label.vocab.freqs.most_common()):
    print(f"{tag}\t\t{count}\t\t{percent*100:4.1f}%")

Tag		Count		Percentage

NN		6131		13.2%
NNP		5104		11.0%
IN		4852		10.4%
DT		3990		 8.6%
NNS		2966		 6.4%
JJ		2948		 6.3%
,		2526		 5.4%
.		1917		 4.1%
VBD		1518		 3.3%
RB		1463		 3.1%
CD		1414		 3.0%
VB		1178		 2.5%
CC		1124		 2.4%
VBZ		1097		 2.4%
TO		1015		 2.2%
VBN		1012		 2.2%
PRP		929		 2.0%
VBG		740		 1.6%
VBP		717		 1.5%
MD		405		 0.9%
PRP$		404		 0.9%
``		402		 0.9%
POS		398		 0.9%
''		393		 0.8%
$		336		 0.7%
:		285		 0.6%
WDT		199		 0.4%
JJR		155		 0.3%
WP		135		 0.3%
RP		134		 0.3%
NNPS		94		 0.2%
WRB		91		 0.2%
JJS		90		 0.2%
RBR		85		 0.2%
-RRB-		55		 0.1%
-LRB-		52		 0.1%
EX		48		 0.1%
RBS		19		 0.0%
LS		10		 0.0%
PDT		9		 0.0%
WP$		6		 0.0%
FW		2		 0.0%
UH		1		 0.0%
SYM		1		 0.0%
#		1		 0.0%


In [329]:
BATCH_SIZE = 4

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits(
    (train_data, val_data, test_data),
    batch_size = BATCH_SIZE,
    device = device,
    sort_key = lambda x: len(x.text),
    sort_within_batch=False,
    repeat=False)

In [330]:
class BiLSTMPOSTagger(nn.Module):
    def __init__(self, 
                 input_dim, 
                 embedding_dim, 
                 hidden_dim, 
                 output_dim, 
                 n_layers, 
                 bidirectional, 
                 dropout, 
                 pad_idx):
        
        super().__init__()
        
        self.embedding = nn.Embedding(input_dim, embedding_dim, padding_idx = pad_idx)
        self.embedding.weight.requires_grad = False
        self.lstm = nn.LSTM(embedding_dim, 
                            hidden_dim, 
                            num_layers = n_layers, 
                            bidirectional = bidirectional,
                            dropout = dropout if n_layers > 1 else 0)
        
        self.fc = nn.Linear(hidden_dim * 2 if bidirectional else hidden_dim, output_dim)
        
        self.dropout = nn.Dropout(dropout)
        
    def forward(self, text):

        #text = [sent len, batch size]
        
        #pass text through embedding layer
        embedded = self.dropout(self.embedding(text))
        
        #embedded = [sent len, batch size, emb dim]
        
        #pass embeddings into LSTM
        outputs, (hidden, cell) = self.lstm(embedded)
        
        #outputs holds the backward and forward hidden states in the final layer
        #hidden and cell are the backward and forward hidden and cell states at the final time-step
        
        #output = [sent len, batch size, hid dim * n directions]
        #hidden/cell = [n layers * n directions, batch size, hid dim]
        
        #we use our outputs to make a prediction of what the tag should be
        predictions = self.fc(self.dropout(outputs))
        
        #predictions = [sent len, batch size, output dim]
        
        return predictions

## Training the Model

Next, we instantiate the model. We need to ensure the embedding dimensions matches that of the GloVe embeddings we loaded earlier.

The rest of the hyperparmeters have been chosen as sensible defaults, though there may be a combination that performs better on this model and dataset.

The input and output dimensions are taken directly from the lengths of the respective vocabularies. The padding index is obtained using the vocabulary and the `Field` of the text.

In [331]:
INPUT_DIM = len(text.vocab)
EMBEDDING_DIM = 100
HIDDEN_DIM = 128
OUTPUT_DIM = len(label.vocab)
N_LAYERS = 2
BIDIRECTIONAL = True
DROPOUT = 0.25
PAD_IDX = text.vocab.stoi[text.pad_token]

model = BiLSTMPOSTagger(INPUT_DIM, 
                        EMBEDDING_DIM, 
                        HIDDEN_DIM, 
                        OUTPUT_DIM, 
                        N_LAYERS, 
                        BIDIRECTIONAL, 
                        DROPOUT, 
                        PAD_IDX)

We initialize the weights from a simple Normal distribution. Again, there may be a better initialization scheme for this model and dataset.

In [332]:
def init_weights(m):
    for name, param in m.named_parameters():
        nn.init.normal_(param.data, mean = 0, std = 0.1)
        
model.apply(init_weights)

BiLSTMPOSTagger(
  (embedding): Embedding(3389, 100, padding_idx=1)
  (lstm): LSTM(100, 128, num_layers=2, dropout=0.25, bidirectional=True)
  (fc): Linear(in_features=256, out_features=46, bias=True)
  (dropout): Dropout(p=0.25, inplace=False)
)

Next, a small function to tell us how many parameters are in our model. Useful for comparing different models.

In [333]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f'The model has {count_parameters(model):,} trainable parameters')

The model has 642,606 trainable parameters


We'll now initialize our model's embedding layer with the pre-trained embedding values we loaded earlier.

This is done by getting them from the vocab's `.vectors` attribute and then performing a `.copy` to overwrite the embedding layer's current weights.

In [334]:
pretrained_embeddings = text.vocab.vectors

print(pretrained_embeddings.shape)

torch.Size([3389, 100])


In [335]:
model.embedding.weight.data.copy_(pretrained_embeddings)

tensor([[-1.1393, -0.1594, -0.2476,  ...,  0.1944, -0.0490, -0.0355],
        [-0.2024, -0.2193, -0.7918,  ..., -2.2743, -1.2092,  0.4288],
        [-0.1077,  0.1105,  0.5981,  ..., -0.8316,  0.4529,  0.0826],
        ...,
        [ 0.0638,  0.0505, -0.0947,  ...,  0.0947, -0.3449,  0.0679],
        [ 0.3079, -0.6757,  0.2158,  ...,  0.3156,  0.5600,  0.4885],
        [-0.3110, -0.3398,  1.0308,  ...,  0.5317,  0.2836, -0.0640]])

It's common to initialize the embedding of the pad token to all zeros. This, along with setting the `padding_idx` in the model's embedding layer, means that the embedding should always output a tensor full of zeros when a pad token is input.

In [336]:
model.embedding.weight.data[PAD_IDX] = torch.zeros(EMBEDDING_DIM)

print(model.embedding.weight.data)

tensor([[-1.1393, -0.1594, -0.2476,  ...,  0.1944, -0.0490, -0.0355],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.1077,  0.1105,  0.5981,  ..., -0.8316,  0.4529,  0.0826],
        ...,
        [ 0.0638,  0.0505, -0.0947,  ...,  0.0947, -0.3449,  0.0679],
        [ 0.3079, -0.6757,  0.2158,  ...,  0.3156,  0.5600,  0.4885],
        [-0.3110, -0.3398,  1.0308,  ...,  0.5317,  0.2836, -0.0640]])


We then define our optimizer, used to update our parameters w.r.t. their gradients. We use Adam with the default learning rate.

In [337]:
optimizer = optim.Adam(model.parameters())

Next, we define our loss function, cross-entropy loss.

Even though we have no `<unk>` tokens within our tag vocab, we still have `<pad>` tokens. This is because all sentences within a batch need to be the same size. However, we don't want to calculate the loss when the target is a `<pad>` token as we aren't training our model to recognize padding tokens.

We handle this by setting the `ignore_index` in our loss function to the index of the padding token in our tag vocabulary.

In [338]:
TAG_PAD_IDX = label.vocab.stoi[label.pad_token]

criterion = nn.CrossEntropyLoss(ignore_index = TAG_PAD_IDX)

We then place our model and loss function on our GPU, if we have one.

In [339]:
model = model.to(device)
criterion = criterion.to(device)

We will be using the loss value between our predicted and actual tags to train the network, but ideally we'd like a more interpretable way to see how well our model is doing - accuracy.

The issue is that we don't want to calculate accuracy over the `<pad>` tokens as we aren't interested in predicting them.

The function below only calculates accuracy over non-padded tokens. `non_pad_elements` is a tensor containing the indices of the non-pad tokens within an input batch. We then compare the predictions of those elements with the labels to get a count of how many predictions were correct. We then divide this by the number of non-pad elements to get our accuracy value over the batch.

In [340]:
def categorical_accuracy(preds, y, tag_pad_idx):
    """
    Returns accuracy per batch, i.e. if you get 8/10 right, this returns 0.8, NOT 8
    """
    max_preds = preds.argmax(dim = 1, keepdim = True) # get the index of the max probability
    non_pad_elements = (y != tag_pad_idx).nonzero()
    correct = max_preds[non_pad_elements].squeeze(1).eq(y[non_pad_elements])
    return correct.sum() / torch.FloatTensor([y[non_pad_elements].shape[0]])

Next is the function that handles training our model.

We first set the model to `train` mode to turn on dropout/batch-norm/etc. (if used). Then we iterate over our iterator, which returns a batch of examples. 

For each batch: 
- we zero the gradients over the parameters from the last gradient calculation
- insert the batch of text into the model to get predictions
- as PyTorch loss functions cannot handle 3-dimensional predictions we reshape our predictions
- calculate the loss and accuracy between the predicted tags and actual tags
- call `backward` to calculate the gradients of the parameters w.r.t. the loss
- take an optimizer `step` to update the parameters
- add to the running total of loss and accuracy

In [341]:
def train(model, iterator, optimizer, criterion, tag_pad_idx):
    
    epoch_loss = 0
    epoch_acc = 0
    
    model.train()
    
    for batch in iterator:
        
        text = batch.text
        tags = batch.label
        
        optimizer.zero_grad()
        predictions = model(text)
        predictions = predictions.view(-1, predictions.shape[-1])
        tags = tags.view(-1)
        
        loss = criterion(predictions, tags)
                
        acc = categorical_accuracy(predictions, tags, tag_pad_idx)
        
        loss.backward()
        
        optimizer.step()
        
        epoch_loss += loss.item()
        epoch_acc += acc.item()
        
    return epoch_loss / len(iterator), epoch_acc / len(iterator)

The `evaluate` function is similar to the `train` function, except with changes made so we don't update the model's parameters.

`model.eval()` is used to put the model in evaluation mode, so dropout/batch-norm/etc. are turned off. 

The iteration loop is also wrapped in `torch.no_grad` to ensure we don't calculate any gradients. We also don't need to call `optimizer.zero_grad()` and `optimizer.step()`.

In [342]:
def evaluate(model, iterator, criterion, tag_pad_idx):
    
    epoch_loss = 0
    epoch_acc = 0
    
    model.eval()
    
    with torch.no_grad():
    
        for batch in iterator:

            text = batch.text
            tags = batch.label
            
            predictions = model(text)
            
            predictions = predictions.view(-1, predictions.shape[-1])
            tags = tags.view(-1)
            
            loss = criterion(predictions, tags)
            
            acc = categorical_accuracy(predictions, tags, tag_pad_idx)

            epoch_loss += loss.item()
            epoch_acc += acc.item()
        
    return epoch_loss / len(iterator), epoch_acc / len(iterator)

Next, we have a small function that tells us how long an epoch takes.

In [343]:
def epoch_time(start_time, end_time):
    elapsed_time = end_time - start_time
    elapsed_mins = int(elapsed_time / 60)
    elapsed_secs = int(elapsed_time - (elapsed_mins * 60))
    return elapsed_mins, elapsed_secs

Finally, we train our model!

After each epoch we check if our model has achieved the best validation loss so far. If it has then we save the parameters of this model and we will use these "best" parameters to calculate performance over our test set.

In [346]:
N_EPOCHS = 25

best_valid_loss = float('inf')

for epoch in range(N_EPOCHS):

    start_time = time.time()
    
    train_loss, train_acc = train(model, train_iterator, optimizer, criterion, TAG_PAD_IDX)
    valid_loss, valid_acc = evaluate(model, valid_iterator, criterion, TAG_PAD_IDX)
    
    end_time = time.time()

    epoch_mins, epoch_secs = epoch_time(start_time, end_time)
    
    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        torch.save(model.state_dict(), 'tut1-model.pt')
    
    print(f'Epoch: {epoch+1:02} | Epoch Time: {epoch_mins}m {epoch_secs}s')
    print(f'\tTrain Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}%')
    print(f'\t Val. Loss: {valid_loss:.3f} |  Val. Acc: {valid_acc*100:.2f}%')

Epoch: 01 | Epoch Time: 1m 28s
	Train Loss: 2.270 | Train Acc: 37.95%
	 Val. Loss: 1.634 |  Val. Acc: 56.36%
Epoch: 02 | Epoch Time: 1m 31s
	Train Loss: 1.531 | Train Acc: 57.33%
	 Val. Loss: 1.138 |  Val. Acc: 69.34%
Epoch: 03 | Epoch Time: 1m 33s
	Train Loss: 1.180 | Train Acc: 67.02%
	 Val. Loss: 0.913 |  Val. Acc: 74.04%
Epoch: 04 | Epoch Time: 1m 23s
	Train Loss: 0.994 | Train Acc: 71.60%
	 Val. Loss: 0.808 |  Val. Acc: 76.84%
Epoch: 05 | Epoch Time: 1m 27s
	Train Loss: 0.874 | Train Acc: 74.55%
	 Val. Loss: 0.720 |  Val. Acc: 78.82%
Epoch: 06 | Epoch Time: 1m 27s
	Train Loss: 0.800 | Train Acc: 76.31%
	 Val. Loss: 0.671 |  Val. Acc: 80.17%
Epoch: 07 | Epoch Time: 1m 29s
	Train Loss: 0.754 | Train Acc: 77.76%
	 Val. Loss: 0.630 |  Val. Acc: 81.31%
Epoch: 08 | Epoch Time: 1m 26s
	Train Loss: 0.707 | Train Acc: 78.96%
	 Val. Loss: 0.598 |  Val. Acc: 82.13%
Epoch: 09 | Epoch Time: 1m 32s
	Train Loss: 0.674 | Train Acc: 79.87%
	 Val. Loss: 0.582 |  Val. Acc: 82.35%
Epoch: 10 | Epoch T

We then load our "best" parameters and evaluate performance on the test set.

In [347]:
model.load_state_dict(torch.load('tut1-model.pt'))

test_loss, test_acc = evaluate(model, test_iterator, criterion, TAG_PAD_IDX)

print(f'Test Loss: {test_loss:.3f} |  Test Acc: {test_acc*100:.2f}%')

Test Loss: 0.360 |  Test Acc: 88.40%


## Inference

88% accuracy looks pretty good, but let's see our model tag some actual sentences.

We define a `tag_sentence` function that will:
- put the model into evaluation mode
- tokenize the sentence with spaCy if it is not a list
- lowercase the tokens if the `Field` did
- numericalize the tokens using the vocabulary
- find out which tokens are not in the vocabulary, i.e. are `<unk>` tokens
- convert the numericalized tokens into a tensor and add a batch dimension
- feed the tensor into the model
- get the predictions over the sentence
- convert the predictions into readable tags

As well as returning the tokens and tags, it also returns which tokens were `<unk>` tokens.

In [304]:
def tag_sentence(model, device, sentence, text_field, tag_field):
    
    model.eval()
    
    if isinstance(sentence, str):
        nlp = spacy.load('en')
        tokens = [token.text for token in nlp(sentence)]
    else:
        tokens = [token for token in sentence]

    if text_field.lower:
        tokens = [t.lower() for t in tokens]
        
    numericalized_tokens = [text_field.vocab.stoi[t] for t in tokens]

    unk_idx = text_field.vocab.stoi[text_field.unk_token]
    
    unks = [t for t, n in zip(tokens, numericalized_tokens) if n == unk_idx]
    
    token_tensor = torch.LongTensor(numericalized_tokens)
    
    token_tensor = token_tensor.unsqueeze(-1).to(device)
         
    predictions = model(token_tensor)
    
    top_predictions = predictions.argmax(-1)
    
    predicted_tags = [tag_field.vocab.itos[t.item()] for t in top_predictions]
    
    return tokens, predicted_tags, unks

We'll get an already tokenized example from the training set and test our model's performance.

In [272]:
example_index = 1

sentence = vars(train_data.examples[example_index])['text']
actual_tags = vars(train_data.examples[example_index])['label']

print(sentence)

['rudolph', 'agnew', ',', '55', 'years', 'old', 'and', 'former', 'chairman', 'of', 'consolidated', 'gold', 'fields', 'plc', ',', 'was', 'named', 'a', 'nonexecutive', 'director', 'of', 'this', 'british', 'industrial', 'conglomerate', '.']


We can then use our `tag_sentence` function to get the tags. Notice how the tokens referring to subject of the sentence, the "respected cleric", are both `<unk>` tokens!

In [273]:
tokens, pred_tags, unks = tag_sentence(model, 
                                       device, 
                                       sentence, 
                                       text, 
                                       label)

print(unks)

['agnew', 'conglomerate']


We can then check how well it did. Surprisingly, it got every token correct, including the two that were unknown tokens!

In [274]:
print("Pred. Tag\tActual Tag\tCorrect?\tToken\n")

for token, pred_tag, actual_tag in zip(tokens, pred_tags, actual_tags):
    correct = '✔' if pred_tag == actual_tag else '✘'
    print(f"{pred_tag}\t\t{actual_tag}\t\t{correct}\t\t{token}")

Pred. Tag	Actual Tag	Correct?	Token

NNP		NNP		✔		rudolph
NNP		NNP		✔		agnew
NNP		,		✘		,
NNP		CD		✘		55
NN		NNS		✘		years
NNP		JJ		✘		old
NNP		CC		✘		and
NNP		JJ		✘		former
NNP		NN		✘		chairman
IN		IN		✔		of
NNP		NNP		✔		consolidated
NNP		NNP		✔		gold
NNP		NNP		✔		fields
NNP		NNP		✔		plc
NNP		,		✘		,
NNP		VBD		✘		was
NNP		VBN		✘		named
NN		DT		✘		a
NN		JJ		✘		nonexecutive
NN		NN		✔		director
IN		IN		✔		of
NN		DT		✘		this
NN		JJ		✘		british
NN		JJ		✘		industrial
NN		NN		✔		conglomerate
NN		.		✘		.


Let's now make up our own sentence and see how well the model does.

Our example sentence below has every token within the model's vocabulary.

Looking at the sentence it seems like it gave sensible tags to every token!

In [206]:
print("Pred. Tag\tToken\n")

for token, tag in zip(tokens, tags):
    print(f"{tag}\t\t{token}")

Pred. Tag	Token

tensor([3, 4, 5, 4])		j.p.
tensor([3, 6, 2, 1])		bolduc
tensor([3, 1, 6, 2])		,
tensor([10, 10,  6,  1])		vice
tensor([28,  5,  5, 11])		chairman
tensor([ 3,  2, 10, 12])		of
tensor([16,  3, 13, 13])		w.r.
tensor([ 3,  5, 15, 15])		grace
tensor([1, 5, 7, 3])		&
tensor([10,  2,  2,  1])		co.
tensor([4, 3, 5, 5])		,
tensor([ 1, 14,  2, 14])		which
tensor([ 2, 11,  1, 12])		holds
tensor([28, 12,  5,  4])		a
tensor([ 3,  4, 17,  6])		83.4
tensor([3, 1, 6, 1])		%
tensor([3, 2, 5, 2])		interest
tensor([13,  1,  2,  1])		in
tensor([3, 1, 1, 5])		this
tensor([3, 8, 5, 2])		energy-services
tensor([8, 2, 8, 4])		company
tensor([3, 3, 4, 1])		,
tensor([ 2, 14,  6,  2])		was
tensor([20,  7,  6,  5])		elected
tensor([ 9,  4,  1, 12])		a
tensor([ 9,  1,  1, 13])		director
tensor([ 8, 14,  2, 19])		.
tensor([ 3, 11,  4, 29])		he
tensor([14,  4,  9,  2])		succeeds
tensor([4, 1, 6, 9])		terrence
tensor([ 6, 13,  5,  5])		d.
tensor([ 6, 15, 12,  2])		daniels
tensor([18,  6,  2,  7])		,
